config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :share_videos
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root 'share_videos#index'
end

app/models/share_video.rb
# frozen_string_literal: true

class ShareVideo < ApplicationRecord
  belongs_to :user

  before_create :update_title_and_desc
  after_create :send_delay_notification

  # If you dont use sidekiq, uncomment the following line
  # after_create :broadcast_notification

  validates_format_of :url, with: %r{\A(https?://)?(www\.)?(youtube\.com/watch\?v=|youtu\.be/)[\w-]{11}(&[\w=&]*)*\z},
                            message: 'must be a valid YouTube URL'

  private

  def update_title_and_desc
    video_service = ShareVideosService.new self
    video_service.update_info
    self
  end

  # If you dont use sidekiq, uncomment the following line
  # def broadcast_notification
  #   ActionCable.server.broadcast('share_video_notifications_channel',
  #                                { type: :new_share_video, metadata: as_json, message: 'New video shared!' })
  # end

  def send_delay_notification
    NotificationJob.perform_now('share_video_notifications_channel',
                                { type: :new_share_video, metadata: as_json, message: 'New video shared!' })
  end
end

app/controllers/share_videos_controller.rb
# frozen_string_literal: true

class ShareVideosController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_share_video, only: %i[show edit update destroy]

  # GET /share_videos or /share_videos.json
  def index
    @share_videos = ShareVideo.includes(:user).all
  end

  # GET /share_videos/1 or /share_videos/1.json
  def show; end

  # GET /share_videos/new
  def new
    @share_video = ShareVideo.new
  end

  # GET /share_videos/1/edit
  def edit; end

  # POST /share_videos or /share_videos.json
  def create
    @share_video = current_user.share_videos.new(share_video_params)

    respond_to do |format|
      if @share_video.save
        format.html { redirect_to share_videos_url, notice: 'Share video was successfully created.' }
        format.json { render :show, status: :created, location: @share_video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @share_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /share_videos/1 or /share_videos/1.json
  def update
    respond_to do |format|
      if @share_video.update(share_video_params)
        format.html { redirect_to share_video_url(@share_video), notice: 'Share video was successfully updated.' }
        format.json { render :show, status: :ok, location: @share_video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @share_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /share_videos/1 or /share_videos/1.json
  def destroy
    @share_video.destroy

    respond_to do |format|
      format.html { redirect_to share_videos_url, notice: 'Share video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_share_video
    @share_video = ShareVideo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def share_video_params
    params.require(:share_video).permit(:url, :title, :description, :user_id)
  end
end

app/helpers/share_videos_helper.rb
# frozen_string_literal: true

module ShareVideosHelper
end

app/views/share_videos/_form.html.erb
<%= form_with(model: share_video) do |form| %>
  <div class="space-y-12">
    <div class="border border-gray-900/10 pb-12">
      <% if share_video.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(share_video.errors.count, "error") %> prohibited this share_video from being saved:</h2>

          <ul>
            <% share_video.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="m-10 grid grid-cols-1 gap-x-6 gap-y-8 ">
        <div class="sm:col-span-4">
          <%= form.label :url, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600">
              <%= form.text_field :url ,class: "block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
            </div>
          </div>
        </div>
      </div>

      <div class="m-10 mb-0 flex items-center justify-start gap-x-6">
        <%= link_to "Cancel", share_videos_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
        <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
      </div>
    </div>
  </div>
<% end %>

app/views/share_videos/_share_video.html.erb
<div id="<%= dom_id share_video %>" class="flex flex-wrap gap-4 pb-2 border-b">
  <div class="flex-initial h-64 w-62">
  <iframe width="auto" height="100%"
    src="https://www.youtube.com/embed/tgbNymZ7vqY">
    </iframe>
  </div>
  <div class="flex-1">
    <h3 class="font-mono font-black text-red-500"> <%= share_video.title %> Lorem </h3>

    <p>
      <strong>Description:</strong>
      <%= share_video.description %>
    </p>

    <p>
      <strong>Share by: </strong>
      <%= share_video&.user&.email %>
    </p>
  </div>


</div>

app/views/share_videos/edit.html.erb
<h1>Editing share video</h1>

<%= render "form", share_video: @share_video %>

<br>

<div>
  <%= link_to "Show this share video", @share_video %> |
  <%= link_to "Back to share videos", share_videos_path %>
</div>

app/views/share_videos/index.html.erb
<div class="my-10 mx-5">

<h1 class="mx-auto font-mono font-black text-2xl my-10">Share videos</h1>

<%= link_to "New share video", new_share_video_path, class: "block mb-5 p-1" %>

<div id="share_videos">
  <% @share_videos.each do |share_video| %>
    <%= render share_video %>
  <% end %>
</div>


</div>

app/views/share_videos/new.html.erb
<h1 class="mx-auto font-mono font-black text-2xl my-10">Share videos</h1>

<%= render "form", share_video: @share_video %>

<br>

app/views/share_videos/show.html.erb
<%= render @share_video %>